// Executed on round finish and will check all users in the championship for badge rewards.
export const badgeLogic = () => {
  const awardedDescs = [
    "Adj removed a competitior.",
    "Adjudicator deducted points.",
    "Be Adjudicator.",
    "Be demoted from competitor.",
    "Be last in a round.",
    "Be promoted to competitor.",
    "Be runner up 3 times.",
    "Bet on driver Q1 finish.",
    "Bet on Podium Finish.",
    "Champ finish no points.",
    "Champ Finish top 3.",
    "Championship Win!",
    "Compete in every round.",
    "Deducted Points Adjudicator.",
    "Did Not Finish. (DNF)",
    "Did not start. (DNS)",
    "Different bet 6 rounds.",
    "Driver No Points Win.",
    "Even points streak 4.",
    "First champ round win.",
    "First Win ever.",
    "Have same points as 2 others.",
    "Have same points as 3 others.",
    "Jakob win and top 5.",
    "Joined championship.",
    "Last 3 with no points.",
    "Last at Champ finish.",
    "Lose to Max 8 times.",
    "Lose with a Ferrari.",
    "Lose with a Mercedes.",
    "No Points after 10 rounds.",
    "No points round closest.",
    "No Points Round.",
    "No points when Dale won.",
    "No vote for 1 round.",
    "No vote for 3 rounds.",
    "No vote for 7 rounds.",
    "Nobody knows...",
    "Nobody won a round.",
    "Oldest driver win.",
    "Point Lead 6.",
    "Point scored every round.",
    "Points 20 when max points 2.",
    "Points in a row 2.",
    "Points streak 10.",
    "Points streak 6.",
    "Q length shorter than 2:15h.",
    "Runner up with a Ferrari.",
    "Same bet twice no points.",
    "Tallest driver win.",
    "Two Championship Win streak!",
    "Wet Runner Up.",
    "Wet Win.",
    "Win 10 dry rounds.",
    "Win 12 rounds in a champ.",
    "Win 2 times in a row.",
    "Win 3 times in a row.",
    "Win 5 times in a row.",
    "Win 6 rounds in a champ.",
    "Win After 3 week break.",
    "Win after Christmas.",
    "Win after Independence Day.",
    "Win after Jurr Park release.",
    "Win after no bet last round.",
    "Win after no points 12 rounds.",
    "Win after no points 6 rounds.",
    "Win after Nowruz Fest.",
    "Win after StarTrek aired.",
    "Win after the Grand National.",
    "Win first of Tripple Header.",
    "Win heaviest driver.",
    "Win last round of champ.",
    "Win Single Header.",
    "Win then no win 5.",
    "Win when Aston Martin P1.",
    "Win when NOR P1.",
    "Win when RIC in Q3.",
    "Win when Thomas last.",
    "Win when VER P1",
    "Win with 10 players.",
    "Win with a McLaren.",
    "Win with a Mexican driver.",
    "Win with Alpine.",
    "Win with an Aston Martin.",
    "Win with Aston Podium.",
    "Win with Moustache driver.",
    "Win with RBR dobule podium.",
    "Win with RBR not in Q3.",
    "Win with team mate P9.",
  ]

  return awardedDescs.sort((a, b) => a.localeCompare(b))
}
